### ISSUE TITLE
prometheus-grafana AWS EBS 연결

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-infra#40]
# Description

# To do
- [x] EBS 생성
- [x] 프로메테우스 메트릭 ebs에 저장
- [ ] 용량 초과시 과거 데이터부터 삭제

# Test Checklist

**Comment by hihahayoung** [comment]
## Chamgo

https://github.com/prometheus-operator/prometheus-operator/issues/2305

https://github.com/elastic/helm-charts/issues/656

https://github.com/prometheus-operator/prometheus-operator/issues/1121

https://velog.io/@chan9708/%EC%BF%A0%EB%B2%84%EB%84%A4%ED%8B%B0%EC%8A%A4-%EB%B3%BC%EB%A5%A8-%EC%82%AC%EC%9A%A9%EB%B2%95

**Comment by hihahayoung** [comment]
@junha-ahn 용량 초과시 자동으로 삭제하는 기능은 없는 듯?

https://stackoverflow.com/questions/58765551/what-happens-when-a-persistence-volume-claim-exceeds-storage

https://stackoverflow.com/questions/55259927/kubernetes-persistence-volume-and-persistence-volume-claim-exceeded-storage

**Comment by junha-ahn** [comment]
@hihahayoung  프로메테우스나 그라파나에서 설정으로 지정할 수 있을까요?

**Comment by hihahayoung** [comment]
@junha-ahn 일단 그런 예시는 찾아봐도 없긴 하네요. 다들 S3로 옮기든지 해서 해결하는 듯 합니다.

**Comment by junha-ahn** [comment]
음 그러면 다들 로그가 쌓일때는 직접 해결해야하는건가요?... 이런 

1. 프로메테우스 alert를 설정 문제 상황에 엔지니어가 해결
2. 또는 자동화 스크립트 등을 이용

일단 그러면 과거데이터 삭제는 무시하시고 하시죠.

**Comment by hihahayoung** [comment]
![스크린샷, 2023-09-17 22-24-13](https://github.com/f-lab-clone/ticketing-infra/assets/59460178/e275a99c-9454-479f-a280-07a209aff7fb)

```
문제 1: storageclass.storage.k8s.io "storage" not found

```

**Comment by hihahayoung** [comment]
## 권한 문제 지속해서 발생

![image](https://github.com/f-lab-clone/ticketing-infra/assets/59460178/b6b17ebd-4678-4182-a7e7-1b9afb275ae0)

새로운 PersistentVolume을 생성하라는 Claim까지는 정상적으로 생성되고, 요청도 제대로 가지만, 권한 문제로 PV가 생성이 안 되는 상황.

현재 코드는 다음과 같다.

```
# Helm Chart를 통해 EBS CSI 드라이버 설치

resource "helm_release" "ebs_csi_driver" {
  name       = "aws-ebs-csi-driver"
  namespace  = "kube-system"
  repository = "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
  chart      = "aws-ebs-csi-driver"

  set {
    name  = "controller.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    type  = "string"
    value = module.ebs_csi_eks_role.iam_role_arn
  }
}
```
```
# 새로운 Role 생성

module "ebs_csi_eks_role" {
  source    = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  role_name = "ebs_csi"

  # 밑에서 csi driver를 통해 생성한 policy를 attach
  attach_ebs_csi_policy = true

  oidc_providers = {
    main = {
      provider_arn               =  module.eks.oidc_provider_arn
      namespace_service_accounts = ["default:ticketing-ebs"]
    }
  }
}
```
*Terraform apply 이후 `aws iam list-attached-role-policies --role-name ebs_csi --query AttachedPolicies[].PolicyArn --output text` 명령어를 치면 role이 제대로 생성된 것을 알 수 있다. 

```
# 새로운 storage class 생성
resource "kubernetes_storage_class" "gp3-storage" {
  depends_on = [helm_release.ebs_csi_driver, module.ebs_csi_eks_role]
  metadata {
    name = "gp3-storage"
    # annotations = {
    #   "storageclass.kubernetes.io/is-default-class" = "true"
    # }
  }
  storage_provisioner = "ebs.csi.aws.com"
  volume_binding_mode = "WaitForFirstConsumer"
  allow_volume_expansion = true
  parameters = {
    "encrypted" = "false"
    "fsType" = "ext4"
    "type" = "gp3"
  }
}
```

**Comment by hihahayoung** [comment]
## 참고자료

https://stackoverflow.com/questions/74716594/how-to-change-default-k8s-cluster-storageclass-with-terraform
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/storage_class
https://github.com/raj13aug/eks_ebs/blob/main/main.tf
https://www.youtube.com/watch?v=lJapZWA1IFk

**Comment by junha-ahn** [comment]
# Storage Class 차이 (Why GP3)

출처
- https://peterica.tistory.com/231

EBS 볼륨은 포맷되지 않은 원시 블록 장치처럼 작동하여 인스턴스(EC2)의 디바이스로 탑재할 수 있다.
- Amazon EBS는 사용한 만큼만 비용을 지불한다.

EBS gp2 불륨의 한계성
- 시스템이 요구하는 적정량의 IOPS를 위해 스토리지의 용량을 필요 이상으로 증가 시킬 수 밖에 없는 구조
- 즉 용량 증가가 없다면 더 높은 IOPS를 구성할 수 없다 (고성능 IO가 필요하지만, 용량은 필요하지 않다면, 병목 또는 비효율성 발생)

EBS gp3 볼륨
- 용량과 IOPS 처리량을 별도로 늘릴 수 있다.
- gp3의 최고 성능은 gp2 볼륨의 최대 처리량보다 4배 빠르지만 gp3 볼륨은 범용 SSD(gp2) 볼륨보다 GiB당 20% 저렴하다


# EKS EBS 사용하기

출처
- https://hyperconnect.github.io/2021/07/05/ebs-csi-gp3-support.html

AWS console 또는 API를 사용하여 **EBS volume을 생성**하고, EC2 instance에 붙이게 되면 Linux가 해당 volume을 **device로 인식**하게 됩니다


## PV, PVC and StorageClass

Pod은 container 기술을 사용하여 구현되므로, Pod이 삭제되게 되면 container 내부의 모든 파일이 삭제됩니다. 데이터를 영구적으로 저장할 수 있도록 Kubernetes에서는 Persistent Volume (**PV**)와 Persistent Volume Claim (**PVC**) [[6]](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)라는 기능을 제공

### PV 

PV는 Kubernetes node처럼 **cluster 단위의 resource**이며, 보통 관리자가 생성하거나 **PVC로부터 동적으로 생성**된다.

**PV는 물리적인 volume**을 나타내며, NFS나 EBS 같이 다양한 방법으로 구현할 수 있다.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tmp
    server: 127.0.0.1 
```

>  NFS를 사용하는 PV object에는 **NFS 서버의 ip**가 기록되어있습니다.

### PVC 

PVC는 Pod처럼 namespace 단위의 resource이며, 보통 사용자가 생성

사용자가 PVC를 생성할 때 사용할 용량, access mode 또는 다른 옵션 등을 설정하면 요청과 **일치하는 PV나 요청에 맞는 PV가 동적으로 생성**되어 **PVC와 1대 1 binding** 됩니다.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

일반적으로 AWS와 같은 cloud 환경에서는 **PVC만 사용자가 직접 선언하여 생성**하고, PV는 동적 생성 기능으로 자동 생성된 것을 사용합니다. 

PVC를 사용해 PV를 동적으로 생성하려면 **StorageClass를 정의**해야 합니다. 

EKS cluster를 생성하면 기본 `StorageClass`가 같이 생성됩니다.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
```

Provisioner는 **StorageClass의 설정**과 PVC의 설정을 읽어 AWS EBS 등 물리적인 volume과 PV object 생성을 담당합니다. 

위의 StorageClass는 Kubernetes source code 내부에 존재하는 AWS EBS provisioner를 사용하고 있고, 추가적으로 type: gp2와 fsType: ext4 옵션을 전달하도록 설정하고 있습니다. 

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs
  namespace: default
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
- 위 PVC와 같이 `.spec.storageClassName`을 사용하여 `StorageClass`를 지정하면 **자동으로 5Gi의 용량을 가지는 gp2 type의 EBS가 생성**되며, PV object 또한 생성됩니다.

### What is CSI Driver?

위 단락의 StorageClass 설명에는 매우 불편한 점을 찾을 수 있습니다. 

Kubernetes source code 내부에 존재하는 AWS EBS provisioner는 당연히 Kubernetes release lifecycle을 따라서 배포되므로, provisioner 신규 기능을 사용하기 위해서는 Kubernetes version을 업그레이드해야 하는 제약 사항이 있습니다.

따라서, Kubernetes 개발자는 Kubernetes 내부에 내장된 provisioner (in-tree)를 모두 삭제하고, **별도의 controller Pod을 통해 동적 provisioning을 사용할 수 있도록 만들었습니다**. 

이것이 바로 CSI (Container Storage Interface) driver [[7]](https://kubernetes-csi.github.io/docs/introduction.html)입니다.

AWS EBS 역시 Amazon EBS CSI driver[[8]](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html)를 사용하여 **동적으로 provisioning 할 수 있습니다**

그러면 이제 ebs.csi.aws.com provisioner를 사용하는 StorageClass를 아래와 같이 추가할 수 있습니다. 이후에는 in-tree StorageClass를 사용했던 것처럼 PVC object를 생성하면 됩니다.

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-csi
provisioner: ebs.csi.aws.com # <----
parameters:
  type: gp2
  fsType: ext4
```
