### ISSUE TITLE
Helm chart repository 

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-infra#49]
# Description

현재 외부 Repo에 존재하는 Chart를 해당 Repo의 하위 폴더로 이동

# To do

# Test Checklist
- [x] ArgoCD 정상 배포

**Comment by junha-ahn** [comment]
## 문제점 

targetRevision 변경으로 다른 브랜치 참고가 가능하다.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/f-lab-clone/ticketing-infra.git
    targetRevision: HEAD
    path: src/kubernetes/ticketing-chart
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
```
